# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190730_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post', verbose_name='评论文章'),
        ),
    ]
