# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-02 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20190730_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siderbar',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='标题'),
        ),
    ]
