# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190728_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uv',
        ),
    ]
